<?php

namespace FunPro\DriverBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CarRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRouteRepository extends EntityRepository
{
}
