<?php

namespace FunPro\DriverBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FunPro\DriverBundle\Entity\Driver;

/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends EntityRepository
{
    public function getAllFilterByDriverQueryBuilder(Driver $driver)
    {
        $qb = $this->createQueryBuilder('c');
        return $qb
            ->select(array('c', 'p'))
            ->innerJoin('c.plaque', 'p')
            ->where($qb->expr()->eq('c.driver', ':driver'))
            ->setParameter('driver', $driver);
    }
}
