<?php

namespace FunPro\DriverBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FunPro\DriverBundle\Entity\Car;
use FunPro\GeoBundle\Doctrine\ValueObject\Point;

/**
 * driverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DriverRepository extends EntityRepository
{
    /**
     * @TODO: Use Spatial Mysql Distance function for Mysql > 5.6.1
     *
     * @param Point   $point
     * @param integer $distance radius in meter
     *
     * @return array
     */
    public function getAllFreeDriverAroundPoint(Point $point, $distance)
    {
        $queryBuilder = $this->createQueryBuilder('dr');

        $queryBuilder->select(array('dr', 'de', 'c', 'w'))
            ->innerJoin('dr.devices', 'de')
            ->innerJoin('dr.cars', 'c')
            ->innerJoin('c.wakeful', 'w')
            ->where($queryBuilder->expr()->eq('c.current', ':current'))
            ->andWhere($queryBuilder->expr()->in('c.status', ':carStatus'))
            ->andWhere($queryBuilder->expr()->lte('glength(linestring(w.point, st_geomfromtext(:location)))', ':distance'))
            ->setParameter('current', true)
            ->setParameter('carStatus', array(Car::STATUS_WAKEFUL, Car::STATUS_SERVICE_IN, Car::STATUS_SERVICE_END))
            ->setParameter('location', $point)
            ->setParameter('distance', $distance / 100000);

        return $queryBuilder->getQuery()
            ->getResult();
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getAllDriversQueryBuilder()
    {
        $queryBuilder = $this->createQueryBuilder('d');
        return $queryBuilder;
    }

    /**
     * @param $driverId
     *
     * @return mixed
     * @throws \Doctrine\ORM\NoResultException
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getWithCar($driverId)
    {
        $queryBuilder = $this->createQueryBuilder('d');

        return $queryBuilder->select(array('d', 'c'))
            ->innerJoin('d.cars', 'c')
            ->where($queryBuilder->expr()->eq('c.current', true))
            ->andWhere($queryBuilder->expr()->eq('d.id', ':id'))
            ->setParameter('id', $driverId)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
