<?php

namespace FunPro\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * driverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class driverRepository extends EntityRepository
{
}
