<?php

namespace FunPro\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarketerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketerRepository extends EntityRepository
{
}
