<?php

namespace FunPro\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * marketerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class marketerRepository extends EntityRepository
{
}
