<?php

namespace FunPro\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CanceledReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanceledReasonRepository extends EntityRepository
{
}
