<?php

namespace FunPro\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FunPro\ServiceBundle\Entity\CanceledReason;

/**
 * CanceledReasonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CanceledReasonRepository extends EntityRepository
{
    public function findAllFilterByGroup($group)
    {
        $qb = $this->createQueryBuilder('c');

        return $qb->select('c')
            ->where($qb->expr()->orX(
                $qb->expr()->eq('c.groups', CanceledReason::GROUP_PUBLIC),
                $qb->expr()->eq('c.groups', ':group')
            ))
            ->setParameter('group', $group)
            ->getQuery()
            ->getResult();
    }
}
