<?php

namespace FunPro\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PropagationListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropagationListRepository extends EntityRepository
{
}
