<?php

namespace FunPro\ServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;
use FunPro\ServiceBundle\Entity\Service;
use FunPro\ServiceBundle\Entity\ServiceLog;

/**
 * ServiceLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceLogRepository extends EntityRepository
{
    /**
     * Get current|last status of service
     *
     * @param Service $service
     *
     * @throws NoResultException
     * @throws NonUniqueResultException
     *
     * @return ServiceLog
     */
    public function getLastLog(Service $service)
    {
        $queryBuilder = $this->createQueryBuilder('s');

        return $queryBuilder->where($queryBuilder->expr()->eq('s.service', ':service'))
            ->orderBy('s.atTime', 'DESC')
            ->setParameter('service', $service)
            ->getQuery()
            ->setMaxResults(1)
            ->getSingleResult();
    }
}
