<?php

namespace FunPro\PassengerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PassengerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PassengerRepository extends EntityRepository
{
    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function getQueryBuilder()
    {
        $qb = $this->createQueryBuilder('p');
        return $qb;
    }
}
