<?php

namespace FunPro\FinancialBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BaseCostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseCostRepository extends EntityRepository
{
    public function getLast()
    {
        return $this->createQueryBuilder('bc')
            ->select('bc')
            ->setMaxResults(1)
            ->orderBy('bc.createdAt', 'DESC')
            ->getQuery()
            ->getSingleResult();
    }
}
