<?php

namespace FunPro\FinancialBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CurrencyExchangeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyExchangeLogRepository extends EntityRepository
{
}
