<?php

namespace FunPro\FinancialBundle\Repository;

use CrEOF\Spatial\PHP\Types\Geometry\Point;
use Doctrine\ORM\EntityRepository;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository
{
    public function getAvailableInRegion(Point $point)
    {
        $queryBuilder = $this->createQueryBuilder('c');

        return $queryBuilder->innerJoin('c.regions', 'r')
            ->where(('ST_Contains(r.region, geomfromtext(:point)) = true'))
            ->setParameter('point', $point)
            ->getQuery()
            ->getResult();
    }
}
