<?php

namespace FunPro\FinancialBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FunPro\GeoBundle\Doctrine\ValueObject\Point;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository
{
    public function getAvailableInRegion(Point $point)
    {
        $queryBuilder = $this->createQueryBuilder('c');

        return $queryBuilder->innerJoin('c.regions', 'r')
            ->where(('ST_Contains(r.region, point_str(:point)) = true'))
            ->setParameter('point', $point)
            ->getQuery()
            ->getResult();
    }
}
