<?php

namespace FunPro\FinancialBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FunPro\PassengerBundle\Entity\Passenger;

/**
 * FavoriteDiscountCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteDiscountCodesRepository extends EntityRepository
{
    public function deactiveCodes(Passenger $passenger)
    {
        $qb = $this->createQueryBuilder('fdc');

        $qb->update()
            ->set('fdc.active', ':status')
            ->where($qb->expr()->eq('fdc.passenger', ':passenger'))
            ->setParameter('status', 0)
            ->setParameter('passenger', $passenger)
            ->getQuery()
            ->execute();
    }
}
