<?php

namespace FunPro\FinancialBundle\Repository;

use Doctrine\ORM\EntityRepository;
use FunPro\FinancialBundle\Entity\DiscountCode;
use FunPro\PassengerBundle\Entity\Passenger;

/**
 * FavoriteDiscountCodesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavoriteDiscountCodesRepository extends EntityRepository
{
    public function deactiveCodes(Passenger $passenger)
    {
        $qb = $this->createQueryBuilder('fdc');

        $qb->update()
            ->set('fdc.active', ':status')
            ->where($qb->expr()->eq('fdc.passenger', ':passenger'))
            ->setParameter('status', 0)
            ->setParameter('passenger', $passenger)
            ->getQuery()
            ->execute();
    }

    public function getUsageCount(DiscountCode $code, Passenger $passenger=null)
    {
        $qb = $this->createQueryBuilder('dc');

        $qb->select($qb->expr()->count('dc.id'))
            ->where($qb->expr()->eq('dc.discountCode', ':code'))
            ->setParameter('code', $code);

        if ($passenger) {
            $qb->andWhere($qb->expr()->eq('dc.passenger', ':passenger'))
                ->setParameter('passenger', $passenger);
        }

        return $qb->getQuery()
        ->getSingleScalarResult();
    }
}
